application: knktechnologytasks
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: assets

- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico
  
- url: /.*
  script: main.py